export default Actions = {
    //handle loading
    HANDLE_LOADING: 'HANDLE_LOADING',

    //handle success
    REQUEST_SUCCESS: 'REQUEST_SUCCESS',
    CLEAR_SUCCESS: 'CLEAR_SUCCESS',

    //handle error
    REQUEST_ERROR: 'REQUEST_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR',

    LOGIN_AGAIN: 'LOGIN_AGAIN',

    //login
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    // get loan
    GETLOAN_REQUEST: "GETLOAN_REQUEST",
    GETLOAN_SUCCESS: "GETLOAN_SUCCESS",
    GETLOAN_FAILURE: "GETLOAN_FAILURE",
    //POST 
    POST_REQUEST: "POST_REQUEST",
    POST_SUCCESS: "POST_SUCCESS",
    POST_FAILURE: "POST_FAILURE",


    // GET DATA
    GET_DATA_REQUEST: "GET_DATA_REQUEST",
    GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
    GET_DATA_FAILURE: "GET_DATA_FAILURE"
}